### ISSUE TITLE
Please add a placeholder for claimed blocks

### ISSUE THREAD

**Issue by AsaAlv** [pixar02/Expansions#1]
GriefPrevention Expansion works great, but I really miss a placeholder for number of claimed blocks. Please add. Thanks, Asa

**Comment by srnyx** [comment]
@pixar02 was this ever added? If so, what's the placeholder?

**Comment by pixar02** [comment]
> @pixar02 was this ever added? If so, what's the placeholder?

I think it was:
%griefprevention_claims%
And for a formatted version:
%griefprevention_claims_formatted%

All placeholders are described on the spigot download page.

**Comment by srnyx** [comment]
> > @pixar02 was this ever added? If so, what's the placeholder?
> 
> I think it was: %griefprevention_claims% And for a formatted version: %griefprevention_claims_formatted%
> 
> All placeholders are described on the spigot download page.

That doesn't show claim **blocks** though, only how many claims the player has.

**Comment by pixar02** [comment]
> > > @pixar02 was this ever added? If so, what's the placeholder?
> > 
> > 
> > I think it was: %griefprevention_claims% And for a formatted version: %griefprevention_claims_formatted%
> > All placeholders are described on the spigot download page.
> 
> That doesn't show claim **blocks** though, only how many claims the player has.

You can get the remaining blocks to claim from "%griefprevention_remainingclaims%" and "%griefprevention_remainingclaims_formatted%".
I added 2 different placeholders: 
"%griefprevention_claimedblocks_current%" and "%griefprevention_claimedblocks_total%"


"%griefprevention_claimedblocks_current%" checks the claim you are in and gives you the blocks claimed in it (if you are the **owner** of that claim)
"%griefprevention_claimedblocks_total%" gives you the total amount of claimed blocks

**Comment by srnyx** [comment]
> You can get the remaining blocks to claim from "%griefprevention_remainingclaims%" and "%griefprevention_remainingclaims_formatted%". I added 2 different placeholders: "%griefprevention_claimedblocks_current%" and "%griefprevention_claimedblocks_total%"
> 
> "%griefprevention_claimedblocks_current%" checks the claim you are in and gives you the blocks claimed in it (if you are the **owner** of that claim) "%griefprevention_claimedblocks_total%" gives you the total amount of claimed blocks

How/where can I download the update?

**Comment by pixar02** [comment]
> > You can get the remaining blocks to claim from "%griefprevention_remainingclaims%" and "%griefprevention_remainingclaims_formatted%". I added 2 different placeholders: "%griefprevention_claimedblocks_current%" and "%griefprevention_claimedblocks_total%"
> > "%griefprevention_claimedblocks_current%" checks the claim you are in and gives you the blocks claimed in it (if you are the **owner** of that claim) "%griefprevention_claimedblocks_total%" gives you the total amount of claimed blocks
> 
> How/where can I download the update?

Using the PlaceholderAPI download command (should be updated now) and later today it will be on spigot.
