### ISSUE TITLE
GriefPrevention PAPI not loading?

### ISSUE THREAD

**Issue by ShaneSimpkin** [pixar02/Expansions#3]
Hey,

The PAPI for GriefPrevention isn't working for 1.16?

I've installed other Placeholders for other plugins such as LuckPerms and the %% work fine for them, have also tried {} and [] but it doesn't seem to work.
![image](https://user-images.githubusercontent.com/8602773/89104118-c05a5e80-d40e-11ea-9def-82224033ccdc.png)

**Comment by pixar02** [comment]
If you are using PAPI 2.10.7 or higher, then yes this expansion is broken. 
PAPI is updating their expansion hooks... This expansion is still using the old version. 


I will update it as soon as they release a good documentation about the update.

**Comment by x1p** [comment]
Clues are to be found here: https://www.spigotmc.org/resources/placeholderapi.6245/updates
And there is a discord server in the description.

**Comment by Funny-cube** [comment]
> If you are using PAPI 2.10.7 or higher, then yes this expansion is broken.
> PAPI is updating their expansion hooks... This expansion is still using the old version.
> 
> I will update it as soon as they release a good documentation about the update.

Hello!

We've got plenty of updated information on our wiki, you can find a link to it here: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Hook-into-PlaceholderAPI#adding-placeholders-to-placeholderapi

Thanks,
funnycube

**Comment by pixar02** [comment]
> > If you are using PAPI 2.10.7 or higher, then yes this expansion is broken.
> > PAPI is updating their expansion hooks... This expansion is still using the old version.
> > I will update it as soon as they release a good documentation about the update.
> 
> Hello!
> 
> We've got plenty of updated information on our wiki, you can find a link to it here: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Hook-into-PlaceholderAPI#adding-placeholders-to-placeholderapi
> 
> Thanks,
> funnycube

All the updated info is scattered all over the wiki.
Not all of it is updated. (ex: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/PlaceholderExpansion#with-external-plugin isn't updated "fully", still has .onPlaceholderRequest(...))
There is also no clear difference what they should look like. (I know everyone codes differently) But there is nowhere a list with what the expansion must have to work properly.  I only know those methods form the old version... not the new one

**Comment by ghost** [comment]
I have the same issue. Hope author fix it soon

**Comment by Valareos** [comment]
I am assuming this will be same issue I am having?

From Log:
[10:07:19] [Server thread/WARN]: [PlaceholderAPI] griefprevention is attempting to register placeholders via a PlaceholderHook class which is no longer supported

**Comment by pixar02** [comment]
I uploaded the fixed version on spigot.
Should have it up on the ecloud soon.
